spring:
  datasource:
    url: ${DB_URL:jdbc:sqlserver://localhost:1433;databaseName=EnergiaClaraDB;encrypt=false;trustServerCertificate=true}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:YourStrong!Passw0rd}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect

app:
  jwt:
    secret: ${JWT_SECRET:energiaclara-super-secret-key-32-chars-minimum!!}
    expiration-ms: 86400000

server:
  port: 8080
